name: '定时更新TVBOX内容'
 
on:
  push:
  schedule:
    - cron: '0 21 * * *'

env:
  REPO_URL: ${{ vars.REPO_URL }}
  SEARCH_CONTENT: ${{ vars.SEARCH_CONTENT }}
  REPLACE_CONTENT: ${{ vars.REPLACE_CONTENT }}

jobs:
  cron_task:
    runs-on: ubuntu-latest
    steps:
      - name: '检出仓库代码'
        uses: actions/checkout@v3
        with:
          ssh-key: ${{  secrets.SSH_KEY }}
          fetch-depth: 0
      - name: '更新TVBOX内容'
        run: bash ./update.sh

