name: '定时更新TVBOX内容'
 
on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    environment: ${{ vars.kankan }}
    steps:
      - name: '检出仓库代码'
        uses: actions/checkout@v3
        with:
          ssh-key: ${{  secrets.SSH_KEY }}
          fetch-depth: 0
      - name: '更新TVBOX内容'
        run: bash ./update.sh

